### ISSUE TITLE
Bug: Error from server (ServiceUnavailable): the server is currently

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/azad-kube-proxy#206]
From time to time I see:
`Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods)`
when running normal kubectl commands, I have spoken to some users and they have also seen it.

In nginx I can see the follwing log, so requests is forwarded to the server.
```
192.168.0.1 - - [07/Jun/2021:07:37:05 +0000] "GET /api/v1/namespaces/ingress-nginx/pods/ingress-nginx-controller-7b67744f78-dwlz5 HTTP/2.0" 503 0 "-" "kubectl/v1.21.0 (linux/amd64) kubernetes/cb303e6" 1476 1.004 [azad-kube-proxy-azad-kube-proxy-80] [] 192.168.0.1:8080 0 1.004 503 b8f6d7d65a418a3a597146201eb80b93
```

The only thing I have seen in azad proxy but I don't think it got anything to do with the error:

```
{"level":"info","ts":1623051428.60472,"caller":"azure/groups.go:57","msg":"Synchronized Azure AD groups to cache","groupCount":30,"syncReason":"ticker"}
```

**Comment by simongottschlag** [comment]
Please reopen if you're still seeing this frequently.
