### ISSUE TITLE
Azure AD App Roles

### ISSUE THREAD

**Issue by christophkreutzer** [XenitAB/azad-kube-proxy#419]
Hello,

first thanks for this project!

In a environment I'm working in, there are a lot of groups (and legacy groups from AD). Because of that my organization is reluctant to give wide-range permissions (like Directory.Read.All) on the AAD tenant to "normal" apps.
So we are mostly working with [App Roles](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps), which allows us to map given AAD objects to app-specific roles. We're already using that concept with Argo CD successfully.

In the examples here I've seen there is a filtering option based on prefix. However I haven't seen an option to select which claim to use from the token. Is this currently not implemented or just not documented? (sorry for dumb questions, I'm not that fluent in go)

Also, while starting the azad-kube-proxy, it fails on my dev cluster, probably because of missing AAD permissions (is it possible to disable the group syncing/caching?):
```
{"level":"error","ts":1649135112.9404237,"caller":"azure/groups.go:36","msg":"Unable to get groups","responseCode":403,"error":"GroupsClient.BaseClient.Get(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation.","stacktrace":"github.com/xenitab/azad-kube-proxy/pkg/azure.(*groups).getAllGroups\n\t/workspace/pkg/azure/groups.go:36\ngithub.com/xenitab/azad-kube-proxy/pkg/azure.(*groups).syncAzureADGroupsCache\n\t/workspace/pkg/azure/groups.go:46\ngithub.com/xenitab/azad-kube-proxy/pkg/azure.(*Client).StartSyncGroups\n\t/workspace/pkg/azure/azure.go:129\ngithub.com/xenitab/azad-kube-proxy/pkg/proxy.(*Client).Start\n\t/workspace/pkg/proxy/proxy.go:102\nmain.main\n\t/workspace/cmd/azad-kube-proxy/main.go:73\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
{"level":"error","ts":1649135112.9404852,"caller":"azure/groups.go:48","msg":"Unable to syncronize groups","error":"GroupsClient.BaseClient.Get(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation.","stacktrace":"github.com/xenitab/azad-kube-proxy/pkg/azure.(*groups).syncAzureADGroupsCache\n\t/workspace/pkg/azure/groups.go:48\ngithub.com/xenitab/azad-kube-proxy/pkg/azure.(*Client).StartSyncGroups\n\t/workspace/pkg/azure/azure.go:129\ngithub.com/xenitab/azad-kube-proxy/pkg/proxy.(*Client).Start\n\t/workspace/pkg/proxy/proxy.go:102\nmain.main\n\t/workspace/cmd/azad-kube-proxy/main.go:73\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
{"level":"error","ts":1649135112.9404979,"caller":"azad-kube-proxy/main.go:75","msg":"Proxy server returned error","error":"GroupsClient.BaseClient.Get(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation.","stacktrace":"main.main\n\t/workspace/cmd/azad-kube-proxy/main.go:75\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
```

**Comment by simongottschlag** [comment]
Hi @christophkreutzer!

The main idea of the AAD integration has so far been to integrate with the actual groups and not roles. I think I understand the use case and it would be possible to implement, but requires quite a few changes that we would have to support but not use ourselves. I need to think about this a bit before committing to making the changes.

Ping @bittrance @NissesSenap @phillebaba @jimgus

**Comment by christophkreutzer** [comment]
Hi @simongottschlag,

sorry for the late reply, I've been on holidays for the last two weeks. Thanks first for confirming that it currently doesn't work with App Roles.

After opening the issue here I've seen you listed some alternatives in the Readme, and we will also be looking into jetstack/kube-oidc-proxy or OpenUnison. Pomerium also seems to have the claim hardcoded to groups.

I don't want to rush you into committing on features that you explicitly out-of-scoped, but still thank you very much for the reply!

**Comment by simongottschlag** [comment]
@christophkreutzer no problem at all! Please check back in if it's not possible to solve with any of the others.
