### ISSUE TITLE
Unable to setup on Windows

### ISSUE THREAD

**Issue by WinningtempJonas** [XenitAB/azad-kube-proxy#560]
Steps
1. az login
2. kubectl azad-proxy menu

This lets me choose cluster, but this will give an error

`time="2022-11-30T12:45:14+01:00" level=error msg="Application returned error" ErrorType="\"KubeConfig\"" error="Kube config error: Unable to load file"`

![image](https://user-images.githubusercontent.com/93764030/204790955-1a36249f-bbb2-4d03-908e-a8af4e5b9565.png)

Workaround: Creating file %USERPROFILE%/.kube/config' manually

**Comment by simongottschlag** [comment]
@WinningtempJonas thanks for reporting! From my tests on a Windows 11 machine, #577 resolves the reported issue and will be released shortly.

**Comment by simongottschlag** [comment]
This has now been released with `v0.0.38` :+1:
