### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by recollir** [XenitAB/azad-kube-proxy#93]
Relevant prometheus metrics in addition to the logs would be nice to have. 😏

**Comment by simongottschlag** [comment]
@recollir thank you so much for the feature request! I've added this in #94 and released [`v0.0.12`](https://github.com/XenitAB/azad-kube-proxy/releases/tag/v0.0.12) with it. <3

**Comment by recollir** [comment]
😃 👍
